spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/jremoteEE1blog
    username: root
    password: ${database.password:root}
abc:
  xyz: Our Blog on QA
  wxy: Our Blog on QA